return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 54,
  height = 32,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 24,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "mapa_rato.png",
      id = 2,
      name = "imagem_mapa",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "colisoes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11,
          y = 311,
          width = 99,
          height = 393,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 138.667,
          width = 225.333,
          height = 161.333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 13.3333,
          y = 13.3333,
          width = 420,
          height = 114.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 141.333,
          width = 82.6667,
          height = 118.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 434.667,
          y = 129.333,
          width = 682.667,
          height = 140,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 654.667,
          y = 269.333,
          width = 474.667,
          height = 34.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 869.333,
          y = 312,
          width = 473.333,
          height = 58.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1109.33,
          y = 373.333,
          width = 232,
          height = 53.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1221.33,
          y = 428,
          width = 113.333,
          height = 182.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 116,
          y = 554.667,
          width = 430.667,
          height = 201.333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 546.667,
          y = 698.667,
          width = 446.667,
          height = 93.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 793.333,
          y = 658.667,
          width = 470.667,
          height = 42.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 884,
          y = 625.333,
          width = 60,
          height = 30.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1041.33,
          y = 605.333,
          width = 297.333,
          height = 54.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
