return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 41,
  height = 37,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 11,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "passagem-mapa.png",
      id = 1,
      name = "imagem_mapa",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "colisoes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "parede_esquerda",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 30,
          height = 1196,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "parede_topo_esquerda",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 230,
          height = 400,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "parede_chao_esquerda",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 660,
          width = 230,
          height = 536,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "ponte_topo",
          type = "",
          shape = "rectangle",
          x = 230,
          y = 0,
          width = 570,
          height = 475,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "ponte_chao",
          type = "",
          shape = "rectangle",
          x = 230,
          y = 565,
          width = 570,
          height = 631,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "parede_topo_direita_esq",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 0,
          width = 140,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "parede_topo_direita_dir",
          type = "",
          shape = "rectangle",
          x = 1020,
          y = 0,
          width = 295,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "porta_fundo",
          type = "",
          shape = "rectangle",
          x = 940,
          y = 0,
          width = 80,
          height = 90,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "parede_chao_direita",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 650,
          width = 515,
          height = 546,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "parede_direita",
          type = "",
          shape = "rectangle",
          x = 1295,
          y = 0,
          width = 20,
          height = 1196,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "portais",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 11,
          name = "portal_fase2",
          type = "",
          shape = "rectangle",
          x = 940,
          y = 90,
          width = 80,
          height = 100,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["destino"] = "fase2",
            ["spawnX"] = 280,
            ["spawnY"] = 200
          }
        }
      }
    }
  }
}
