return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 54,
  height = 32,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 5,
  nextobjectid = 38,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "passagem-mapa.png",
      id = 2,
      name = "imagem_mapa",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "colisoes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1.33333,
          y = 180,
          width = 36,
          height = 840,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 34.6667,
          y = 290.667,
          width = 96,
          height = 56,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 346.667,
          width = 49.3333,
          height = 114.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 173.333,
          y = 388,
          width = 94.6667,
          height = 26.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 266.667,
          y = 409.333,
          width = 30.6667,
          height = 29.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 294.667,
          y = 442.667,
          width = 42.6667,
          height = 74.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 43.3332,
          y = 869.333,
          width = 96,
          height = 56,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128.666,
          y = 737.333,
          width = 49.3333,
          height = 132,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 181.999,
          y = 766.667,
          width = 81.3334,
          height = 25.3334,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 254,
          y = 742.667,
          width = 30.6667,
          height = 29.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304.667,
          y = 614.667,
          width = 42.6667,
          height = 74.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 277.333,
          y = 721.333,
          width = 24,
          height = 17.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 296,
          y = 692,
          width = 20,
          height = 26.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 349.333,
          y = 618.667,
          width = 704,
          height = 33.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 338.667,
          y = 492,
          width = 712,
          height = 26.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 754,
          y = 251,
          width = 49,
          height = 241,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 796,
          y = 73,
          width = 156,
          height = 190,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 954,
          y = 48,
          width = 86,
          height = 37,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1019,
          y = 86,
          width = 54,
          height = 98,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1078,
          y = 131,
          width = 87,
          height = 153,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1130,
          y = 284,
          width = 69,
          height = 53,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1179,
          y = 320,
          width = 76,
          height = 69,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1258,
          y = 391,
          width = 49,
          height = 294,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 665,
          width = 139,
          height = 119,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 908,
          y = 984,
          width = 349,
          height = 38,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1155,
          y = 679,
          width = 155,
          height = 61,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1112,
          y = 844,
          width = 44,
          height = 136,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 747,
          width = 29,
          height = 272,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1168,
          y = 928,
          width = 105,
          height = 67,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1242,
          y = 902,
          width = 31,
          height = 21,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 883,
          y = 820,
          width = 49,
          height = 112,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 846,
          y = 791,
          width = 35,
          height = 159,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 893,
          y = 931,
          width = 61,
          height = 45,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "portais",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 952,
          y = 98,
          width = 69,
          height = 98,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["destino"] = "fase2",
            ["spawnX"] = 280,
            ["spawnY"] = 200
          }
        }
      }
    }
  }
}
