return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 41,
  height = 37,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 7,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "Mapa-Inicio.png",
      id = 1,
      name = "imagem_mapa",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "colisoes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "parede_esquerda",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 180,
          height = 1195,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "parede_direita",
          type = "",
          shape = "rectangle",
          x = 1136,
          y = 0,
          width = 180,
          height = 1195,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "parede_topo_esquerda",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 510,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "parede_topo_direita",
          type = "",
          shape = "rectangle",
          x = 806,
          y = 0,
          width = 510,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "parede_caverna_fundo",
          type = "",
          shape = "rectangle",
          x = 510,
          y = 0,
          width = 296,
          height = 140,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "parede_chao_esquerda",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 860,
          width = 510,
          height = 335,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "parede_chao_direita",
          type = "",
          shape = "rectangle",
          x = 806,
          y = 860,
          width = 510,
          height = 335,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "portais",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "portal_caverna",
          type = "",
          shape = "rectangle",
          x = 510,
          y = 140,
          width = 296,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["destino"] = "fase1",
            ["spawnX"] = 626,
            ["spawnY"] = 998
          }
        }
      }
    }
  }
}
